### ISSUE TITLE
Enforcing HTTPS

### ISSUE THREAD

**Issue by Frosty-J** [libgdx/libgdx.github.io#64]
Hello, I'm here to raise the discussion of enforcing HTTPS on libgdx.com. This can be toggled in [Settings -> Pages -> Enforce HTTPS](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site).

**Pros:**

* Removes the "not secure" warning when navigating to the website by typing libgdx.com into the address bar.
* Removes the HTTP entries from Bing's (and consequently DuckDuckGo's) index, which ties into the first point but might also bring an SEO benefit? #62 would likely also fix this (sorry, haven't looked into that).
* Should reduce the odds of anything unwanted being injected into the page, such as when on public Wi-Fi.
* Theoretically might be faster, since the HTTP/2 protocol gets used when GitHub Pages is served over HTTPS. In practice it's about the same for me.

**Cons:**

* Can cause compatibility issues with older systems. GitHub uses Let's Encrypt, which has a [compatibility list](https://letsencrypt.org/docs/certificate-compatibility/). Their list is on the cautious side - e.g. Nintendo 3DS is listed as incompatible, but [it works fine](https://user-images.githubusercontent.com/60154347/148701366-64419f8b-224b-4d53-96db-ebcaee311aa0.png) after closing a certificate error message.
* Theoretically might be slower, since the page needs to be encrypted then decrypted. In practice it's about the same for me.

**Comment by crykn** [comment]
Done.

**Comment by Frosty-J** [comment]
I don't mean to be a nuisance, but http://libgdx.com still doesn't redirect to HTTPS, including in an incognito/private/secret window to avoid cache. If you changed something, it's not working.

**Comment by crykn** [comment]
Whoops, apparently disabling and reenabling GH Pages resets the Enforce HTTPS settings. Should be fixed now.
